# Generated by Django 5.0.14 on 2026-02-06 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField()),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('header', 'Custom Header')], default='none', max_length=20)),
                ('bearer_token', models.CharField(blank=True, max_length=500, null=True)),
                ('basic_user', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_pass', models.CharField(blank=True, max_length=255, null=True)),
                ('header_name', models.CharField(blank=True, max_length=255, null=True)),
                ('header_value', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('materialized', 'Materialized'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('row_count_estimate', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('dimensional', 'Dimensional'), ('data_vault', 'Data Vault')], max_length=20)),
                ('hubs', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=list)),
                ('satellites', models.JSONField(blank=True, default=list)),
                ('facts', models.JSONField(blank=True, default=list)),
                ('dimensions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packages', models.ManyToManyField(blank=True, related_name='models', to='core.datapackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('s3', 'S3'), ('clickhouse', 'ClickHouse')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('endpoint', models.URLField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('access_key_id', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_access_key', models.CharField(blank=True, max_length=255, null=True)),
                ('path_style', models.BooleanField(default=False)),
                ('tls_verify', models.BooleanField(default=True)),
                ('mode', models.CharField(blank=True, choices=[('single', 'Single'), ('cluster', 'Cluster')], max_length=20, null=True)),
                ('hosts', models.JSONField(blank=True, default=list)),
                ('database', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('secure', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_backends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datapackage',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='core.storagebackend'),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('body_template', models.TextField(blank=True, null=True)),
                ('pagination', models.JSONField(blank=True, default=dict)),
                ('preview_json', models.JSONField(blank=True, null=True)),
                ('inferred_schema', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='core.apisource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datapackage',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.stream'),
        ),
    ]
