# Generated by Django 5.0.14 on 2026-02-06 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stream",
            name="api_source",
        ),
        migrations.AddField(
            model_name="stream",
            name="source_object",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="stream",
            name="method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="stream",
            name="path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("database", "Database"),
                            ("s3", "S3"),
                            ("sftp", "SFTP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(blank=True, null=True)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("bearer", "Bearer Token"),
                            ("basic", "Basic Auth"),
                            ("header", "Custom Header"),
                            ("ssh_key", "SSH Key"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "bearer_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("basic_user", models.CharField(blank=True, max_length=255, null=True)),
                ("basic_pass", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "header_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "header_value",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "database_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("mongodb", "MongoDB"),
                            ("sqlserver", "SQL Server"),
                            ("oracle", "Oracle"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255, null=True)),
                ("port", models.IntegerField(blank=True, null=True)),
                (
                    "database_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("s3_endpoint", models.URLField(blank=True, null=True)),
                ("s3_region", models.CharField(blank=True, max_length=100, null=True)),
                ("s3_bucket", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "s3_access_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "s3_secret_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sftp_host", models.CharField(blank=True, max_length=255, null=True)),
                ("sftp_port", models.IntegerField(blank=True, default=22, null=True)),
                (
                    "sftp_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sftp_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sftp_key", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stream",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streams",
                to="core.datasource",
            ),
        ),
        migrations.DeleteModel(
            name="ApiSource",
        ),
    ]
