# Generated by Django 5.0.14 on 2026-02-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_datapackage_file_path_datapackage_file_size_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='data_package_name_pattern',
            field=models.CharField(blank=True, help_text="Pattern for naming data packages, e.g., '{stream_name}_{date}_{time}'", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='incremental_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='ingestion_strategy',
            field=models.CharField(blank=True, choices=[('full_refresh', 'Full Refresh'), ('incremental', 'Incremental Load'), ('snapshot', 'Snapshot')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='s3_file_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='s3_path_pattern',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='schedule_cron',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='schedule_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stream',
            name='schedule_interval_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='schema',
            field=models.JSONField(blank=True, help_text='User-defined schema for the stream', null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='sftp_file_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='sftp_path_pattern',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
