# Generated by Django 5.0.14 on 2026-02-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_datapackage_external_s3_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="records_selector",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
