# Generated by Django 5.2.11 on 2026-02-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stream_records_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebackend',
            name='password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='storagebackend',
            name='secret_access_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
