# Generated by Django 5.0.14 on 2026-02-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_storagebackend_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="packages",
        ),
        migrations.AddField(
            model_name="model",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="models", to="core.topic"
            ),
        ),
    ]
