# Generated by Django 5.0.14 on 2026-02-14 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_change_model_from_packages_to_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="table_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="model",
            name="table_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="model",
            name="clickhouse_backend",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind": "clickhouse"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="models",
                to="core.storagebackend",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="core.model",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="data_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="core.datapackage",
            ),
        ),
    ]
