# Generated by Django 5.0.14 on 2026-02-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_table_tracking_and_model_runs"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagebackend",
            name="cluster_name",
            field=models.CharField(
                blank=True,
                help_text="ClickHouse cluster name (required for cluster mode)",
                max_length=255,
                null=True,
            ),
        ),
    ]
