# Generated by Django 5.0.14 on 2026-02-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_cluster_name_to_storagebackend"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagebackend",
            name="is_cluster",
            field=models.BooleanField(
                default=False,
                help_text="Auto-detected: Whether ClickHouse is running in cluster mode",
            ),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="detected_cluster_name",
            field=models.CharField(
                blank=True,
                help_text="Auto-detected cluster name from ClickHouse",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="cluster_nodes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Auto-detected list of cluster nodes",
            ),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="cluster_metadata_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time cluster metadata was detected/updated",
                null=True,
            ),
        ),
    ]
