name: Build and Deploy to Development

on:
  pull_request:
    branches:
      - main

jobs:
  build-ui-files:
    runs-on: self-hosted
    name: Build UI Files

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Environment
        run: make env
        
      - name: Build UI files
        run: |
          npm --prefix=frontend run build

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: node-modules-${{ hashFiles('frontend/package.json') }}

      - name: Cache Python venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: python-venv-${{ hashFiles('pyproject.toml') }}

      - name: Upload UI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ui-files
          path: |
            frontend/dist

  build-multiarch-internal-ui:
    name: Build and Push Multi-Arch UI Image (Internal)
    needs: build-ui-files
    uses: fricker-studios/github-actions/.github/workflows/build-multiarch-image.yml@main
    with:
      dockerfile_path: Dockerfile.nginx
      image_name: ${{ vars.INTERNAL_REGISTRY_URL }}/internal/etl-ui
      registry: ${{ vars.INTERNAL_REGISTRY_URL }}
      push: true
      tags: |
        pr-${{ github.event.pull_request.number }}-${{ github.run_number }}
      download_artifacts: true
      artifact_name: ui-files
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  update-gitops-manifest:
    name: Update GitOps Manifest (Development)
    needs: build-multiarch-internal-ui
    uses: fricker-studios/github-actions/.github/workflows/update-gitops-manifest.yml@main
    with:
      image_tag: pr-${{ github.event.pull_request.number }}-${{ github.run_number }}
      gitops_repo: fricker-studios/gitops-dev
      project_source_dir: etl
    secrets:
      GITOPS_ACCESS_TOKEN: ${{ secrets.GITOPS_PAT }}

  argocd-sync:
    name: ArgoCD Sync Application (Development)
    needs: update-gitops-manifest
    uses: fricker-studios/github-actions/.github/workflows/argocd-sync.yml@main
    with:
      application: etl-dev
    secrets:
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}