name: Release to Production

on:
  push:
    tags:
      - '*'

jobs:
  build-ui-files:
    runs-on: self-hosted
    name: Build UI Files

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Environment
        run: make env

      - name: Build UI files
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_SENTRY_RELEASE: ${{ github.ref_name }}
          VITE_SENTRY_ENVIRONMENT: prod
          VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          npm --prefix=frontend run build

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: node-modules-${{ hashFiles('frontend/package.json') }}

      - name: Cache Python venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: python-venv-${{ hashFiles('pyproject.toml') }}

      - name: Upload UI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ui-files
          path: |
            frontend/dist

  build-multiarch-internal-ui:
    name: Build and Push Multi-Arch UI Image (Internal)
    needs: build-ui-files
    uses: fricker-studios/github-actions/.github/workflows/build-multiarch-image.yml@main
    with:
      dockerfile_path: Dockerfile.nginx
      image_name: ${{ vars.INTERNAL_REGISTRY_URL }}/internal/etl-ui
      registry: ${{ vars.INTERNAL_REGISTRY_URL }}
      push: true
      tags: |
        ${{ github.ref_name }}
      download_artifacts: true
      artifact_name: ui-files
      artifact_path: "frontend/dist"
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  update-gitops-manifest:
    name: Update GitOps Manifest (Production)
    needs: build-multiarch-internal-ui
    uses: fricker-studios/github-actions/.github/workflows/update-gitops-manifest.yml@main
    with:
      image_tag: ${{ github.ref_name }}
      gitops_repo: fricker-studios/gitops-prod
      project_source_dir: etl
    secrets:
      GITOPS_ACCESS_TOKEN: ${{ secrets.GITOPS_PAT }}

  update-demo-manifest:
    name: Update GitOps Manifest (Demo)
    needs: build-multiarch-internal-ui
    uses: fricker-studios/github-actions/.github/workflows/update-gitops-manifest.yml@main
    with:
      image_tag: ${{ github.ref_name }}
      gitops_repo: fricker-studios/gitops-demo
      project_source_dir: etl
    secrets:
      GITOPS_ACCESS_TOKEN: ${{ secrets.GITOPS_PAT }}

  argocd-sync-prod:
    name: ArgoCD Sync Application (Production)
    needs: update-gitops-manifest
    uses: fricker-studios/github-actions/.github/workflows/argocd-sync.yml@main
    with:
      application: etl-prod
    secrets:
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}

  argocd-sync-demo:
    name: ArgoCD Sync Application (Demo)
    needs: update-demo-manifest
    uses: fricker-studios/github-actions/.github/workflows/argocd-sync.yml@main
    with:
      application: etl-demo
    secrets:
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}

  create-release:
    name: Create GitHub Release
    needs: [build-multiarch-internal-ui, update-gitops-manifest, update-demo-manifest]
    uses: fricker-studios/github-actions/.github/workflows/github-release.yml@main
    with:
      tag: ${{ github.ref_name }}
      generate_notes: true
    secrets:
      gh_token: ${{ secrets.GITOPS_PAT }}

  create-sentry-release:
    name: Create Sentry Release
    needs: [build-multiarch-internal-ui, update-gitops-manifest, update-demo-manifest]
    uses: fricker-studios/github-actions/.github/workflows/sentry-release.yml@main
    with:
      release_version: ${{ github.ref_name }}
      sentry_org: sentry
      sentry_project: etl
      sentry_url: https://sentry.alexfricker.com/
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
